/* Generated By:JavaCC: Do not edit this line. TrabalhoCompConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TrabalhoCompConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int DO = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int FUNCTION = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int ACHAVES = 17;
  /** RegularExpression Id. */
  int FCHAVES = 18;
  /** RegularExpression Id. */
  int APARENTESES = 19;
  /** RegularExpression Id. */
  int FPARENTESES = 20;
  /** RegularExpression Id. */
  int PTVIRGULA = 21;
  /** RegularExpression Id. */
  int VIRGULA = 22;
  /** RegularExpression Id. */
  int ATRIBUICAO = 23;
  /** RegularExpression Id. */
  int SOMA = 24;
  /** RegularExpression Id. */
  int SUB = 25;
  /** RegularExpression Id. */
  int MULT = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int MENOR = 30;
  /** RegularExpression Id. */
  int MAIOR = 31;
  /** RegularExpression Id. */
  int IGUAL = 32;
  /** RegularExpression Id. */
  int NUM = 33;
  /** RegularExpression Id. */
  int ID = 34;
  /** RegularExpression Id. */
  int LETRA = 35;
  /** RegularExpression Id. */
  int DIGITO = 36;
  /** RegularExpression Id. */
  int DIGITOS = 37;
  /** RegularExpression Id. */
  int LETRAOUDIGITO = 38;
  /** RegularExpression Id. */
  int FRACAO = 39;
  /** RegularExpression Id. */
  int EXPOENTE = 40;
  /** RegularExpression Id. */
  int FINALSUBLINHADO = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"var\"",
    "\"int\"",
    "\"bool\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"return\"",
    "\"print\"",
    "\"function\"",
    "\"true\"",
    "\"false\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "<NUM>",
    "<ID>",
    "<LETRA>",
    "<DIGITO>",
    "<DIGITOS>",
    "<LETRAOUDIGITO>",
    "<FRACAO>",
    "<EXPOENTE>",
    "<FINALSUBLINHADO>",
  };

}
